#!/usr/bin/env bash

readonly WORKING_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly DOTBOT_DIRNAME="dotbot"
readonly CONFIG_FILENAME="install.conf.json"

# Change to dotfiles directory.
cd "$WORKING_DIR"

# Initialize dotbot directory.
git submodule update --init --recursive "$DOTBOT_DIRNAME"

# Bootstrap dotfiles.
"$WORKING_DIR/$DOTBOT_DIRNAME/bin/dotbot" -d "$WORKING_DIR" -c "$CONFIG_FILENAME" $@
