#!/usr/bin/env bash

# Make vim backup directory
mkdir -p ~/.vim-backup ~/.vim-swap

# Make empty directory for tmuxifier layouts
mkdir -p ~/.tmuxifier-layouts

# Install plugins
vim --not-a-term +PlugInstall +qa
$HOME/.external/fzf/install --completion --key-bindings --no-update-rc

# Neovim configuration
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -fs ~/.vim $XDG_CONFIG_HOME/nvim
ln -fs ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
